spring.application.name=apprenant-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/certif_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=9a615631cd197629b35bc20c586111f185799c96191c96443685c7031201047d
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-http-post-size=20MB

# Debugging security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

server.error.include-message=always
